#!/bin/sh

NAME=${NAME:-battery}

BATT_REMAINING=$(pmset -g batt | grep -Eo "[0-9]+%" | cut -d% -f1)
if pmset -g batt | grep -q 'AC Power'; then
  ICON="󰂄"
else
ICONS=("󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
ICON="${ICONS[$(( BATT_REMAINING / 10 < 10 ? BATT_REMAINING / 10 : 10 ))]}"
fi
sketchybar --set battery icon="$ICON" --set "$NAME" label="$BATT_REMAINING%"
