#!/bin/sh

VOLUME=$(osascript -e 'output volume of (get volume settings)')
MUTED=$(osascript -e 'output muted of (get volume settings)')

if [ "$MUTED" = "true" ]; then
  ICON="󰖁"
  sketchybar --set "$NAME" icon="$ICON" label="mute"
else
  if [ "$VOLUME" -ge 70 ]; then
    ICON="󰕾"
  elif [ "$VOLUME" -ge 30 ]; then
    ICON="󰖀"
  else
    ICON="󰕿"
  fi
  sketchybar --set "$NAME" icon="$ICON" label="$VOLUME%"
fi
