#!/bin/sh

set -e

arch="$(uname -m)"
pid="$$"
mkdir "/tmp/$pid"

sudo pacman -Syyuu \
  fakeroot \
  zip \
  unzip \
  make \
  wget \
  openssh \
  base-devel \
  git \
  docker \
  mariadb-clients \
  nodejs \
  yarn \
  pnpm \
  deno \
  go \
  fish \
  tig \
  neovim \
  tmux \
  fzf \
  jq \
  mandoc \
  texlive-most \
  mkcert \
  clang \
  dstat \
  whois \
  dig \
  ngrok \
  hey \
  ffmpeg \
  rsync \
  htop \
  hugo \
  apache \
  python-pip \
  aws-cli-v2 \
  pacman-contrib \
  ghostscript \
  mandoc \
  texlive # textlive-most 

git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si

yay -Syyuu pandoc-bin ghq-bin aws-sam-cli-bin aws-session-manager-plugin evans-bin k6 

pip install --user localstack

sudo systemctl enable --now sshd

git clone https://github.com/KidsCannon/commandline-tools.git ~/.k8n/commandline-tools
. "$HOME/.k8n/commandline-tools/init.sh"
append-line-if-not-exists 'source "$HOME/.k8n/commandline-tools/init.sh"' ~/.bashrc

append-line-if-not-exists 'PATH="$HOME/go/bin:$PATH"' ~/.bashrc

# Go applications
go install github.com/Songmu/ghg/cmd/ghg@v0.3.0
append-line-if-not-exists 'PATH="$(ghg bin):$PATH"' ~/.bashrc
go install github.com/fujimura/git-gsub@v0.1.2

# Binaries hosted on Github Releases
## ghg get motemen/ghq

# Docker
sudo gpasswd -a $USER docker
sudo systemctl enable --now docker

# Docker Compose
(
  cd "/tmp/$pid"
  wget "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-${arch}"
  mkdir -p ~/.docker/cli-plugins
  mv docker-compose-linux-x86_64 ~/.docker/cli-plugins/docker-compose
  chmod +x $HOME/.docker/cli-plugins/docker-compose
)

## asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0
source "$HOME/.asdf/asdf.sh"
append-line-if-not-exists 'source "$HOME/.asdf/asdf.sh"' ~/.bashrc
append-line-if-not-exists 'source "$HOME/.asdf/completions/asdf.bash"' ~/.bashrc
echo 'legacy_version_file = yes' > ~/.asdfrc

asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin add go-sdk https://github.com/yacchi/asdf-go-sdk.git
# asdf plugin add awscli https://github.com/MetricMike/asdf-awscli.git

asdf install nodejs lts-gallium
# asdf install awscli 2.5.6

asdf global nodejs lts-gallium
# asdf global awscli 2.5.6

## SDKMAN
curl -s https://get.sdkman.io | bash

## Fisher
curl -sL https://git.io/fisher | source
fisher install jorgebucaran/fisher
fisher install reitzig/sdkman-for-fish

## Link config
ln -sf "$HOME/config/.gitconfig" ~/.gitconfig
ln -sf "$HOME/config/.gitignore_global" ~/.gitignore_global
ln -sf "$HOME/config/.config/fish" ~/.config/fish
ln -sf "$HOME/config/.config/nvim" ~/.config/nvim
ln -sf "$HOME/config/.tmux.conf" ~/.tmux.conf

## UTF-8
sudo append-line-if-not-exists 'en_US.UTF-8 UTF-8' /etc/locale.gen
sudo append-line-if-not-exists 'ja_JP.UTF-8 UTF-8' /etc/locale.gen
sudo locale-gen

rm "/tmp/$pid"
